package processing.test.androidtutorial_feedyourworms;

/* autogenerated by Processing revision 1310 on 2025-11-06 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class AndroidTutorial_FeedYourWorms extends PApplet {

int STROKE_WIDTH = 20;
int WORM_COUNT = 50;

Worm[] worms = new Worm[WORM_COUNT];
WormController wormController = new WormController();
ArrayList<Food> foods = new ArrayList<Food>();
int lastTime = 0;

public void setup() {
  //size(640, 360);//фіксований розмір
  /* size commented out by preprocessor */;//додати у випадку Android
  wormController.setWorldSize(width, height);
  for (int i=0; i<WORM_COUNT; i++) {
    worms[i] = new Worm((int) random(0, width), (int) random(0, height), random(-PI, PI));
  }
  
  strokeWeight(STROKE_WIDTH);
  setupBackground();
}

public void draw() {
  setBackground();
  int currentTime = millis();
  int timeDifference = currentTime - lastTime;

  wormController.moveWorms(worms, timeDifference);
  wormController.calculateIntersections(worms, foods);

  for (int i = 0; i< foods.size(); i++) {
    if (foods.get(i).resource <=0) {
      foods.remove(i);
      break;
    }
  }

  for (int i = 0; i< worms.length; i++) {
    worms[i].drawWorm();
  }

  for (int i=0; i<foods.size(); i++) {
    foods.get(i).drawFood();
  }
  lastTime = currentTime;
}

public void mouseClicked() {
  Food food = new Food(mouseX, mouseY);
  foods.add(food);
}

//розкоментувати у випадку Android
public void touchStarted() {
  for (int i = 0; i < touches.length; i++) {
    Food food = new Food((int) touches[i].x, (int)touches[i].y);
    foods.add(food);
  }
}
// backgroud colors
float currR, currG, currB;
float nextR, nextG, nextB;
float easing = 0.001f;
int lastChange = 0;

public void setupBackground() {
  currR = currG = currB = 25;
  pickNextColor();
}

public void setBackground() {
  background(currR, currG, currB, 100);
  updateCurrColor();
  if (5000 < millis() - lastChange) { 
    pickNextColor();
    lastChange = millis();
  }
}

public void pickNextColor() {
  nextG = random(128);
  nextG = random(128);
  nextB = random(128);
}

public void updateCurrColor() {
  // Easing between current and next colors
  currR += easing * (nextR - currR);
  currG += easing * (nextG - currG);
  currB += easing * (nextB - currB);
}
final int INITIAL_FOOD_SIZE = 5;
final int INITIAL_FOOD_RADIUS = 30;
class Food {
  int x;
  int y;
  int radius = INITIAL_FOOD_RADIUS;
  int resource = INITIAL_FOOD_SIZE;

  Food(int x, int y) {
    this.x = x;
    this.y = y;
  }

  public void drawFood() {
    fill(255);
    ellipse(x, y, radius, radius);
  }

  public void consume() {
    radius = (int) ((float)radius * 0.75f);
    resource--;
  }
}
final float SEGMENT_LENGTH = 20;
final int MAX_CHAIN_COUNT = 30;
final int INITIAL_CHAIN_COUNT = 3;
final int CORNER_ROTATION_UNDEFINED = 0;
final int CORNER_ROTATION_OX = 1;
final int CORNER_ROTATION_OY = 2;

class Worm {
  float[] sx = new float[MAX_CHAIN_COUNT];
  float[] sy = new float[MAX_CHAIN_COUNT];
  float wavePeriod = random(2000, 5000);
  float initialPeriod = random(-PI, PI);
  int chainCount = INITIAL_CHAIN_COUNT;
  int preferedCornerRotation = CORNER_ROTATION_UNDEFINED;

  int R = (int) random(128, 255);
  int G = (int)random(128, 255);
  int B = (int)random(128, 255);

  Worm(int x, int y, float angle) {
    sx[0] = x;
    sy[0] = y;
    sx[1] = x + cos(angle) * SEGMENT_LENGTH;
    sy[1] = y + sin(angle) * SEGMENT_LENGTH;
    sx[2] = sx[1] + cos(angle) * SEGMENT_LENGTH;
    sy[2] = sy[1] + sin(angle) * SEGMENT_LENGTH;
  }

  public void drag(float x, float y) {
    sx[0] = x;
    sy[0] = y;
    for (int i=0; i < min(chainCount, sx.length-1); i++) {
      dragSegment(i+1, sx[i], sy[i]);
    }
  }

  private void dragSegment(int i, float xin, float yin) {
    float dx = xin - sx[i];
    float dy = yin - sy[i];
    float angle = atan2(dy, dx);  
    sx[i] = xin - cos(angle) * SEGMENT_LENGTH;
    sy[i] = yin - sin(angle) * SEGMENT_LENGTH;
  }

  public void drawWorm() {
    for (int i=1; i < min(chainCount, sx.length-1); i++) {
      drawSegment(sx[i-1], sy[i-1], sx[i], sy[i], R, G, B);
    }
  }

  public void drawSegment(float x1, float y1, float x2, float y2, int r, int g, int b) {
    stroke(r, g, b, 100);
    line(x1, y1, x2, y2);
  }

  public void addSegment() {
    chainCount++;
  }
}
float VELOCITY = 140;
int CORNER_CHECK_COEF = 2;
int WALL_CHECK_COEF = 1;

class WormController {
  int worldSizeX = 0;
  int worldSizeY = 0;

  public void setWorldSize(int x, int y) {
    this.worldSizeX = x;
    this.worldSizeY = y;
  }

  public void moveWorms(Worm[] worms, float millis) {
    for (int i = 0; i < worms.length; i++) {
      dragWorm(worms[i], millis);
    }
  }
  
  public void calculateIntersections(Worm[] worms, ArrayList<Food> foods) {
    for (int i = 0; i < worms.length; i++) {
      Worm worm = worms[i];

      for (int j = 0; j < foods.size(); j++) {
        Food food = foods.get(j);
        float distance = sqrt((worm.sx[0] - food.x) * (worm.sx[0] - food.x) +
          (worm.sy[0] - food.y) * (worm.sy[0] - food.y));
        if (distance < food.radius) {
          println("Consume food!");
          food.consume();
          worm.addSegment();
        }
      }
    }
  }
  
  private void dragWorm(Worm worm, float millis) {
    float timeFrame = millis / 1000;
    float angle = getRightAngle(worm) + getAngleShift(worm, timeFrame);

    float distance = timeFrame * VELOCITY;
    float nextX = worm.sx[0] + cos(angle) * distance;
    float nextY = worm.sy[0] + sin(angle) * distance;
    worm.drag(nextX, nextY);
  }
  
  public float getAngleShift(Worm worm, float timeFrame) {
     float angleShift = PI * sin(worm.initialPeriod + 
      ( (float) millis() / worm.wavePeriod)) * timeFrame;
      return angleShift;
  }

  public float getRightAngle(Worm worm) {
    float dx = worm.sx[0] - worm.sx[1];
    float dy = worm.sy[0] - worm.sy[1];

    if (isInCorner(worm)) {
      if (worm.preferedCornerRotation == CORNER_ROTATION_UNDEFINED) {
        boolean isDxBigger = abs(dx) > abs(dy);
        if (isDxBigger) {
          worm.preferedCornerRotation = CORNER_ROTATION_OY;
        } else {
          worm.preferedCornerRotation = CORNER_ROTATION_OX;
        }
      }
      if (worm.preferedCornerRotation == CORNER_ROTATION_OY) {
        dx = 0.01f;//move OY
        if (isTopWall(worm, CORNER_CHECK_COEF)) {
          dy = 1; //DOWN
        } else {
          dy = -1; //UP
        }
      } else {
        dy = 0.01f;//move OX
        if (isLeftWall(worm, CORNER_CHECK_COEF)) {
          dx = 1; //RIGHT
        } else {
          dx = -1;//LEFT
        }
      }
    } else {
      worm.preferedCornerRotation = CORNER_ROTATION_UNDEFINED;
      if (isLeftWall(worm, WALL_CHECK_COEF)) {
        dx = 0.01f;//move OY
      } else if (isRightWall(worm, WALL_CHECK_COEF)) {
        dx = -0.01f; //move OY
      }
      if (isTopWall(worm, WALL_CHECK_COEF)) {
        dy = 0.01f; //move OX
      } else if (isBottomWall(worm, WALL_CHECK_COEF)) {
        dy = -0.01f; //move OX
      }
    }

    return atan2(dy, dx);
  }

  private boolean isInCorner(Worm worm) {
    int closeWalls = 0;

    if (isLeftWall(worm, CORNER_CHECK_COEF)) {
      closeWalls++;
    } else if (isRightWall(worm, CORNER_CHECK_COEF)) {
      closeWalls++;
    }
    if (isTopWall(worm, CORNER_CHECK_COEF)) {
      closeWalls++;
    } else if (isBottomWall(worm, CORNER_CHECK_COEF)) {
      closeWalls++;
    }

    return closeWalls == 2;
  }

  private boolean isLeftWall(Worm worm, int coef) {
    return worm.sx[0] < coef* STROKE_WIDTH;
  }

  private boolean isRightWall(Worm worm, int coef) {
    return worm.sx[0] > worldSizeX - coef * STROKE_WIDTH;
  }

  private boolean isTopWall(Worm worm, int coef) {
    return worm.sy[0] < coef*STROKE_WIDTH;
  }

  private boolean isBottomWall(Worm worm, int coef) {
    return worm.sy[0] > worldSizeY - coef*STROKE_WIDTH;
  }
}


  public void settings() { fullScreen(); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "AndroidTutorial_FeedYourWorms" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
