package processing.test.androidtutorial_feedyourworms;

/* autogenerated by Processing revision 1310 on 2025-11-06 */

import processing.core.*;

import java.util.ArrayList;

public class AndroidTutorial_FeedYourWorms extends PApplet {

    int STROKE_WIDTH = 20;
    int WORM_COUNT = 50;

    Worm[] worms = new Worm[WORM_COUNT];
    WormController wormController = new WormController(this);
    ArrayList<Food> foods = new ArrayList<Food>();
    int lastTime = 0;

    public void setup() {
        //size(640, 360);//фіксований розмір
        /* size commented out by preprocessor */
        ;//додати у випадку Android
        wormController.setWorldSize(width, height);
        for (int i = 0; i < WORM_COUNT; i++) {
            worms[i] = new Worm(this, (int) random(0, width), (int) random(0, height), random(-PI, PI));
        }

        strokeWeight(STROKE_WIDTH);
        setupBackground();
    }

    public void draw() {
        setBackground();
        int currentTime = millis();
        int timeDifference = currentTime - lastTime;

        wormController.moveWorms(worms, timeDifference);
        wormController.calculateIntersections(worms, foods);

        for (int i = 0; i < foods.size(); i++) {
            if (foods.get(i).resource <= 0) {
                foods.remove(i);
                break;
            }
        }

        for (int i = 0; i < worms.length; i++) {
            worms[i].drawWorm();
        }

        for (int i = 0; i < foods.size(); i++) {
            foods.get(i).drawFood();
        }
        lastTime = currentTime;
    }

    public void mouseClicked() {
        Food food = new Food(this, mouseX, mouseY);
        foods.add(food);
    }

    //Add to receive touch events at Android
    public void touchStarted() {
        for (int i = 0; i < touches.length; i++) {
            Food food = new Food(this, (int) touches[i].x, (int) touches[i].y);
            foods.add(food);
        }
    }

    // background colors
    float currR, currG, currB;
    float nextR, nextG, nextB;
    float easing = 0.001f;
    int lastChange = 0;

    public void setupBackground() {
        currR = currG = currB = 25;
        pickNextColor();
    }

    public void setBackground() {
        background(currR, currG, currB, 100);
        updateCurrColor();
        if (5000 < millis() - lastChange) {
            pickNextColor();
            lastChange = millis();
        }
    }

    public void pickNextColor() {
        nextG = random(128);
        nextG = random(128);
        nextB = random(128);
    }

    public void updateCurrColor() {
        // Easing between current and next colors
        currR += easing * (nextR - currR);
        currG += easing * (nextG - currG);
        currB += easing * (nextB - currB);
    }

    public static final int INITIAL_FOOD_SIZE = 5;
    public static final int INITIAL_FOOD_RADIUS = 30;
    public static final float SEGMENT_LENGTH = 20;
    public static final int MAX_CHAIN_COUNT = 30;
    public static final int INITIAL_CHAIN_COUNT = 3;
    public static final int CORNER_ROTATION_UNDEFINED = 0;
    public static final int CORNER_ROTATION_OX = 1;
    public static final int CORNER_ROTATION_OY = 2;

    public static float VELOCITY = 140;
    int CORNER_CHECK_COEF = 2;
    int WALL_CHECK_COEF = 1;


    public void settings() {
        fullScreen();
    }

    static public void main(String[] passedArgs) {
        String[] appletArgs = new String[]{"AndroidTutorial_FeedYourWorms"};
        if (passedArgs != null) {
            PApplet.main(concat(appletArgs, passedArgs));
        } else {
            PApplet.main(appletArgs);
        }
    }
}
