apply plugin: 'com.android.application'

android {
    namespace "processing.test.androidtutorial_feedyourworms"

    sourceSets {
        main {
            jniLibs.srcDirs = ['libs']
        }
    }
    compileSdkVersion 36
    defaultConfig {
        applicationId "processing.test.androidtutorial_feedyourworms"
        minSdkVersion 24
        targetSdkVersion 36
        versionCode 1
        versionName "1.0"
        vectorDrawables.useSupportLibrary = true
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    signingConfigs {
        release {
            if (project.hasProperty('PROCESSING_UPLOAD_KEYSTORE_FILE')) {
                storeFile file(PROCESSING_UPLOAD_KEYSTORE_FILE)
                storePassword PROCESSING_UPLOAD_STORE_PASSWORD
                keyAlias PROCESSING_UPLOAD_KEY_ALIAS
                keyPassword PROCESSING_UPLOAD_KEY_PASSWORD
            }
        }
    }
    buildTypes {
        debug {
            debuggable true
        }
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    lintOptions {
        abortOnError false
    }
    aaptOptions {
        noCompress "tflite"
        noCompress "lite"
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'androidx.appcompat:appcompat:1.6.0'
    implementation files('libs/processing-core.jar')
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
    testImplementation 'junit:junit:4.13'
}

